name: Deploy Backend to Azure App Service

on:
  push:
    branches: [main, master]
    paths:
      - 'backend/**'
      - '.github/workflows/azure-backend.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: neel-ai-analytics-backend # Change this to your Azure app name
  AZURE_WEBAPP_PACKAGE_PATH: './backend'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements-prod.txt

      - name: Set environment variables for build
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          export DJANGO_SETTINGS_MODULE=data_analysis_api.settings_azure
          export SECRET_KEY="build-secret-key"
          export DEBUG=False

      - name: Collect static files
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          export DJANGO_SETTINGS_MODULE=data_analysis_api.settings_azure
          export SECRET_KEY="build-secret-key"
          export DEBUG=False
          python manage.py collectstatic --noinput

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./backend

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
