name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'next.config.ts'
      - 'tsconfig.json'
      - '.github/workflows/github-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: |
          echo "Building Next.js application for static export..."
          npm run build
        env:
          NODE_ENV: production

      - name: Verify build output
        run: |
          echo "Checking build output..."
          if [ -d "out" ]; then
            echo "✅ Static export successful - out directory created"
            echo "Files in out directory:"
            ls -la out/
          else
            echo "❌ Static export failed - no out directory found"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
